export const COLOR_TOKENS = [
	"brand",
	"brand-accent",
	"brand-accent-foreground",
	"background",
	"foreground",
	"card",
	"card-foreground",
	"popover",
	"popover-foreground",
	"primary",
	"primary-foreground",
	"secondary",
	"secondary-foreground",
	"muted",
	"muted-foreground",
	"accent",
	"accent-foreground",
	"selected",
	"selected-foreground",
	"destructive",
	"destructive-foreground",
	"border",
	"input",
	"ring",
	"sidebar",
	"sidebar-foreground",
	"sidebar-accent",
	"sidebar-accent-foreground",
	"sidebar-border",
	"review-comment",
	"review-insertion",
	"review-deletion",
	"review-replacement",
] as const;

export const FOUNDATION_COLOR_TOKENS = [
	"background",
	"foreground",
	"card",
	"primary",
	"primary-foreground",
	"muted",
	"muted-foreground",
	"border",
	"ring",
] as const;

export const SYNTAX_TOKENS = [
	"plain",
	"meta",
	"comment",
	"keyword",
	"variable",
	"string",
	"regexp",
	"number",
	"section",
	"type",
	"attribute",
	"selector",
] as const;

export const TERMINAL_TOKENS = [
	"foreground",
	"background",
	"cursor",
	"cursor-accent",
	"selection-background",
	"selection-foreground",
	"black",
	"red",
	"green",
	"yellow",
	"blue",
	"magenta",
	"cyan",
	"white",
	"bright-black",
	"bright-red",
	"bright-green",
	"bright-yellow",
	"bright-blue",
	"bright-magenta",
	"bright-cyan",
	"bright-white",
] as const;

export type ColorToken = (typeof COLOR_TOKENS)[number];
export type FoundationColorToken = (typeof FOUNDATION_COLOR_TOKENS)[number];
export type SyntaxToken = (typeof SYNTAX_TOKENS)[number];
export type TerminalToken = (typeof TERMINAL_TOKENS)[number];
